def get_event_data():
    [
  {
    "event_id": "EV001",
    "name": "Alumni Tech Meetup 2025",
    "description": "A networking event connecting alumni working in tech roles with final-year students. Includes panel talks, Q&A, and project showcase.",
    "status": "scheduled",
    "date": "2025-01-22",
    "event_type": "Meetup",
    "location": "Auditorium Hall A",
    "organizer": "Alumni Cell",
    "audience": "All Students, Alumni",
    "registration_link": "https://example.com/ev001",
    "created_at": "2024-11-20"
  },
  {
    "event_id": "EV002",
    "name": "Machine Learning Masterclass",
    "description": "Hands-on ML workshop conducted by alumni working at Google. Covers ML pipelines, RAG systems, and interview tips.",
    "status": "done",
    "date": "2024-10-12",
    "event_type": "Workshop",
    "location": "CS Lab 3",
    "organizer": "Dept. of CSE",
    "audience": "3rd & 4th Year Students",
    "registration_link": null,
    "created_at": "2024-08-30"
  },
  {
    "event_id": "EV003",
    "name": "ECE Alumni Industry Talk",
    "description": "Alumni from Qualcomm and Nvidia discuss VLSI trends, internships, and career development.",
    "status": "postponed",
    "date": "2025-02-15",
    "event_type": "Seminar",
    "location": "Virtual (Google Meet)",
    "organizer": "ECE Department",
    "audience": "ECE Students",
    "registration_link": "https://example.com/ev003",
    "created_at": "2024-12-01"
  },
  {
    "event_id": "EV004",
    "name": "Annual Alumni Reunion",
    "description": "Grand alumni gathering with cultural programs, award ceremony, and dinner.",
    "status": "scheduled",
    "date": "2025-03-10",
    "event_type": "Reunion",
    "location": "Main Ground",
    "organizer": "Alumni Association",
    "audience": "Alumni Only",
    "registration_link": "https://example.com/ev004",
    "created_at": "2024-11-01"
  },
  {
    "event_id": "EV005",
    "name": "Career Guidance Week",
    "description": "Series of sessions on placements, resume building, and mock interviews guided by alumni.",
    "status": "TBD",
    "date": null,
    "event_type": "Career Event",
    "location": "TBD",
    "organizer": "Training & Placement Cell",
    "audience": "All Students",
    "registration_link": null,
    "created_at": "2024-12-05"
  },
  {
    "event_id": "EV006",
    "name": "Hackathon: Build for Campus",
    "description": "48-hour hackathon where teams solve real campus problems. Winners get mentorship + cash prize.",
    "status": "scheduled",
    "date": "2025-04-05",
    "event_type": "Hackathon",
    "location": "Innovation Lab",
    "organizer": "Innovation Cell",
    "audience": "All Departments",
    "registration_link": "https://example.com/ev006",
    "created_at": "2024-12-10"
  },
  {
    "event_id": "EV007",
    "name": "Finance & Career Planning Webinar",
    "description": "Alumni working in investment banking share tips on managing money and switching careers.",
    "status": "done",
    "date": "2024-09-18",
    "event_type": "Webinar",
    "location": "Google Meet",
    "organizer": "Alumni Office",
    "audience": "All Years",
    "registration_link": null,
    "created_at": "2024-07-15"
  },
  {
    "event_id": "EV008",
    "name": "Alumni Sports Day",
    "description": "Cricket, football, and fun games with alumni and students.",
    "status": "cancelled",
    "date": "2024-11-28",
    "event_type": "Sports",
    "location": "Sports Ground",
    "organizer": "Sports Club",
    "audience": "Students, Alumni",
    "registration_link": "https://example.com/ev008",
    "created_at": "2024-09-05"
  },
  {
    "event_id": "EV009",
    "name": "Entrepreneurship Roundtable",
    "description": "Discussion with alumni founders on funding, product development, and startup challenges.",
    "status": "scheduled",
    "date": "2025-02-02",
    "event_type": "Roundtable",
    "location": "Seminar Hall 2",
    "organizer": "EDC Cell",
    "audience": "Entrepreneurship Enthusiasts",
    "registration_link": "https://example.com/ev009",
    "created_at": "2024-12-12"
  },
  {
    "event_id": "EV010",
    "name": "Robotics Showcase",
    "description": "Students and alumni showcase robotics projects including drones, automation tools, and AI bots.",
    "status": "TBD",
    "date": null,
    "event_type": "Exhibition",
    "location": "Robotics Lab",
    "organizer": "Robotics Society",
    "audience": "Tech Students",
    "registration_link": null,
    "created_at": "2024-12-15"
  }
]
