def get_demo_data():
    return {
        "alumni": [
            {
                "id": 1,
                "name": "Satyam Singh",
                "designation": "AI/ML Engineer",
                "graduation_year": 2024,
                "company": "NVIDIA",
                "location": "Bengaluru, India",
                "email": "satyam.singh@example.com",
                "phone": "+91-9876543210",
                "skills": ["Deep Learning", "Python", "TensorFlow"],
                "linkedin": "https://linkedin.com/in/satyam-singh"
            },
            {
                "id": 2,
                "name": "Rewant Bhriguvanshi",
                "designation": "Software Engineer",
                "graduation_year": 2023,
                "company": "Google",
                "location": "Hyderabad, India",
                "email": "rewant.b@example.com",
                "phone": "+91-9123456780",
                "skills": ["C++", "Cloud", "System Design"],
                "linkedin": "https://linkedin.com/in/rewant-bhriguvanshi"
            },
            {
                "id": 3,
                "name": "Krishna Yadav",
                "designation": "Startup Founder",
                "graduation_year": 2025,
                "company": "NeuraCore Tech",
                "location": "Noida, India",
                "email": "krishna.yadav@example.com",
                "phone": "+91-9988776655",
                "skills": ["Product Development", "AI Integration"],
                "linkedin": "https://linkedin.com/in/krishna-yadav"
            },
            {
                "id": 4,
                "name": "Garvit Gupta",
                "designation": "Software Engineer",
                "graduation_year": 2025,
                "company": "Flipkart",
                "location": "Bengaluru, India",
                "email": "garvit.gupta@example.com",
                "phone": "+91-9001234567",
                "skills": ["Backend", "Python", "Django"],
                "linkedin": "https://linkedin.com/in/garvit-gupta"
            },
            {
                "id": 5,
                "name": "Shubhika Sinha",
                "designation": "Machine Learning Engineer",
                "graduation_year": 2023,
                "company": "TCS Research",
                "location": "Pune, India",
                "email": "shubhika.sinha@example.com",
                "phone": "+91-9090908080",
                "skills": ["Machine Learning", "NLP", "Model Deployment"],
                "linkedin": "https://linkedin.com/in/shubhika-sinha"
            },
            {
                "id": 6,
                "name": "Prayas Yadav",
                "designation": "Software Engineer",
                "graduation_year": 2024,
                "company": "Uber",
                "location": "Gurgaon, India",
                "email": "prayas.yadav@example.com",
                "phone": "+91-9898987878",
                "skills": ["Go", "Microservices", "API Development"],
                "linkedin": "https://linkedin.com/in/prayas-yadav"
            },
            {
                "id": 7,
                "name": "Shreyas Singh",
                "designation": "VLSI Engineer",
                "graduation_year": 2022,
                "company": "Qualcomm",
                "location": "Hyderabad, India",
                "email": "shreyas.singh@example.com",
                "phone": "+91-9887766554",
                "skills": ["Verilog", "Physical Design", "RTL"],
                "linkedin": "https://linkedin.com/in/shreyas-singh"
            },
            {
                "id": 8,
                "name": "Kirti Yadav",
                "designation": "VLSI Engineer",
                "graduation_year": 2021,
                "company": "AMD",
                "location": "Bengaluru, India",
                "email": "kirti.yadav@example.com",
                "phone": "+91-9876501234",
                "skills": ["FPGA", "ASIC", "Static Timing Analysis"],
                "linkedin": "https://linkedin.com/in/kirti-yadav"
            },
            {
                "id": 9,
                "name": "Raghav Agrawal",
                "designation": "Embedding Engineer",
                "graduation_year": 2025,
                "company": "IIT Delhi Lab",
                "location": "Delhi, India",
                "email": "raghav.agrawal@example.com",
                "phone": "+91-9797976767",
                "skills": ["LLM Embeddings", "Vector Databases", "Semantic Search"],
                "linkedin": "https://linkedin.com/in/raghav-agrawal"
            },
            {
                "id": 10,
                "name": "Gurhans Grover",
                "designation": "Startup Co-Founder",
                "graduation_year": 2023,
                "company": "JuvoAI",
                "location": "Gurgaon, India",
                "email": "gurhans.grover@example.com",
                "phone": "+91-9654321876",
                "skills": ["Full Stack", "Product Design", "React"],
                "linkedin": "https://linkedin.com/in/gurhans-grover"
            },
            {
                "id": 11,
                "name": "Aarav Mehta",
                "designation": "Software Engineer",
                "graduation_year": 2022,
                "company": "Paytm",
                "location": "Noida, India",
                "email": "aarav.mehta@example.com",
                "phone": "+91-9005001001",
                "skills": ["Java", "Spring Boot", "REST APIs"],
                "linkedin": "https://linkedin.com/in/aarav-mehta"
            },
            {
                "id": 12,
                "name": "Tanisha Verma",
                "designation": "Data Analyst",
                "graduation_year": 2023,
                "company": "Accenture",
                "location": "Mumbai, India",
                "email": "tanisha.verma@example.com",
                "phone": "+91-9876123450",
                "skills": ["SQL", "Power BI", "Python"],
                "linkedin": "https://linkedin.com/in/tanisha-verma"
            },
            {
                "id": 13,
                "name": "Yash Rajput",
                "designation": "Software Developer",
                "graduation_year": 2024,
                "company": "Ola Electric",
                "location": "Bengaluru, India",
                "email": "yash.rajput@example.com",
                "phone": "+91-9002345678",
                "skills": ["Node.js", "MongoDB", "Docker"],
                "linkedin": "https://linkedin.com/in/yash-rajput"
            },
            {
                "id": 14,
                "name": "Mehul Jain",
                "designation": "Blockchain Developer",
                "graduation_year": 2025,
                "company": "Polygon Labs",
                "location": "Remote",
                "email": "mehul.jain@example.com",
                "phone": "+91-9877001122",
                "skills": ["Solidity", "Smart Contracts", "DeFi"],
                "linkedin": "https://linkedin.com/in/mehul-jain"
            },
            {
                "id": 15,
                "name": "Simran Kaur",
                "designation": "AI Product Manager",
                "graduation_year": 2021,
                "company": "Adobe",
                "location": "Noida, India",
                "email": "simran.kaur@example.com",
                "phone": "+91-9091332211",
                "skills": ["Product Strategy", "AI UX", "Analytics"],
                "linkedin": "https://linkedin.com/in/simran-kaur"
            },
            {
                "id": 16,
                "name": "Devansh Saxena",
                "designation": "Cybersecurity Engineer",
                "graduation_year": 2023,
                "company": "KPMG",
                "location": "Gurgaon, India",
                "email": "devansh.saxena@example.com",
                "phone": "+91-8800554433",
                "skills": ["Pen Testing", "SIEM", "Network Security"],
                "linkedin": "https://linkedin.com/in/devansh-saxena"
            },
            {
                "id": 17,
                "name": "Ishita Sharma",
                "designation": "Frontend Engineer",
                "graduation_year": 2022,
                "company": "Swiggy",
                "location": "Bengaluru, India",
                "email": "ishita.sharma@example.com",
                "phone": "+91-7001239988",
                "skills": ["React", "Next.js", "UI/UX"],
                "linkedin": "https://linkedin.com/in/ishita-sharma"
            },
            {
                "id": 18,
                "name": "Aditya Chauhan",
                "designation": "Startup Founder",
                "graduation_year": 2024,
                "company": "Aether Robotics",
                "location": "Delhi, India",
                "email": "aditya.chauhan@example.com",
                "phone": "+91-7888991122",
                "skills": ["Robotics", "Hardware Design", "AI"],
                "linkedin": "https://linkedin.com/in/aditya-chauhan"
            },
            {
                "id": 19,
                "name": "Ritika Malhotra",
                "designation": "ML Research Intern",
                "graduation_year": 2025,
                "company": "IIIT Hyderabad",
                "location": "Hyderabad, India",
                "email": "ritika.malhotra@example.com",
                "phone": "+91-7099775533",
                "skills": ["ML", "Python", "Computer Vision"],
                "linkedin": "https://linkedin.com/in/ritika-malhotra"
            },
            {
                "id": 20,
                "name": "Harsh Tandon",
                "designation": "Backend Engineer",
                "graduation_year": 2022,
                "company": "PhonePe",
                "location": "Bengaluru, India",
                "email": "harsh.tandon@example.com",
                "phone": "+91-7999882211",
                "skills": ["Java", "Kubernetes", "Cloud"],
                "linkedin": "https://linkedin.com/in/harsh-tandon"
            }
        ]
    }
